export default {
  SET_PUBLICE: 'SET_PUBLICE',
  SET_ARTICLELIST: 'SET_ARTICLELIST',
  SET_INPUTTEXT: 'SET_INPUTTEXT',
  SET_PUBLICLIST: 'SET_PUBLICLIST',
  SET_TYPELIST: 'SET_TYPELIST',
  SET_ALL_LIST: 'SET_ALL_LIST',
  LOAD_MORE_ALL_LIST: 'LOAD_MORE_ALL_LIST',
  SET_UNSUBSCRIBE: 'SET_UNSUBSCRIBE',
  SET_CANCLICK: 'SET_CANCLICK',
  SET_TOGGLENIGHT: 'SET_TOGGLENIGHT',
  SET_GETTOGGLENIGHT: 'SET_GETTOGGLENIGHT',
  SET_SUBSCRIBE: '',
  SET_NOVICE_STATE: 'SET_NOVICE_STATE',
  SET_NOVICE_GUIDE_STATE: 'SET_NOVICE_GUIDE_STATE'
}
