export default {
  SET_PUBLICE: 'SET_PUBLICE',
  SET_ARTICLELIST: 'SET_ARTICLELIST',
  SET_INPUTTEXT: 'SET_INPUTTEXT',
  SET_PUBLICLIST: 'SET_PUBLICLIST',
  SET_TYPELIST: 'SET_TYPELIST',
  SET_ALL_LIST: 'SET_ALL_LIST',
  LOAD_MORE_ALL_LIST: 'LOAD_MORE_ALL_LIST'
}
